services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: laravel12_apache
    container_name: laravel12_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/php/local-php.ini:/usr/local/etc/php/conf.d/local-php.ini:ro
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel12_mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  adminer:
    image: adminer:latest
    container_name: laravel12_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  db_data:
